// Generated by gencpp from file my_package/Num.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_NUM_H
#define MY_PACKAGE_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_package
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : ranges()  {
    }
  Num_(const ContainerAllocator& _alloc)
    : ranges(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _ranges_type;
  _ranges_type ranges;





  typedef boost::shared_ptr< ::my_package::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_package::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::my_package::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::my_package::Num > NumPtr;
typedef boost::shared_ptr< ::my_package::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_package::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_package::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_package::Num_<ContainerAllocator1> & lhs, const ::my_package::Num_<ContainerAllocator2> & rhs)
{
  return lhs.ranges == rhs.ranges;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_package::Num_<ContainerAllocator1> & lhs, const ::my_package::Num_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_package::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_package::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_package::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b59fbb52705f63cb3fada08d311c9c4d";
  }

  static const char* value(const ::my_package::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb59fbb52705f63cbULL;
  static const uint64_t static_value2 = 0x3fada08d311c9c4dULL;
};

template<class ContainerAllocator>
struct DataType< ::my_package::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_package/Num";
  }

  static const char* value(const ::my_package::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_package::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] ranges\n"
;
  }

  static const char* value(const ::my_package::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_package::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ranges);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_package::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_package::Num_<ContainerAllocator>& v)
  {
    s << indent << "ranges[]" << std::endl;
    for (size_t i = 0; i < v.ranges.size(); ++i)
    {
      s << indent << "  ranges[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ranges[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_NUM_H
